version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.16
    steps:
    - checkout
    - restore_cache:
        keys:
        - go-mod-v1-{{ checksum "go.sum" }}
    - run: go mod download
    - run: go get github.com/jstemmer/go-junit-report
    - save_cache:
        key: go-mod-v1-{{ checksum "go.sum" }}
        paths:
        - "/go/pkg/mod"
    - run: make test coverage
    - store_test_results:
        path: build
    - store_artifacts:
        path: build/coverage.html
        destination: coverage-report.html